#!/usr/bin/env bash

if [ $# -ne 3 ]; then
    echo "Usage: simple-calc <number> <operator> <number>"
    exit 1
fi

NUM1=$1
OP=$2
NUM2=$3

case $OP in
    +)
        echo "$NUM1 + $NUM2 = $((NUM1 + NUM2))"
        ;;
    -)
        echo "$NUM1 - $NUM2 = $((NUM1 - NUM2))"
        ;;
    \*)
        echo "$NUM1 * $NUM2 = $((NUM1 * NUM2))"
        ;;
    /)
        if [ "$NUM2" -eq 0 ]; then
            echo "Error: Division by zero"
            exit 1
        fi
        echo "$NUM1 / $NUM2 = $((NUM1 / NUM2))"
        ;;
    *)
        echo "Unknown operator: $OP"
        echo "Supported operators: +, -, *, /"
        exit 1
        ;;
esac